local_backend: true
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Features"
      name: "features"
      file: "app/content/features.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - label: 'Features'
          name: "features"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - label: "Sub Section"
              name: "subSections"
              widget: "list"
              fields:
                - { label: "Title", name: "title", widget: "string"}
                - { label: "Image", name: "image", widget: "image"}
                - label: "Details"
                  name: "details"
                  widget: "list"
                  fields:
                    - { label: "Description", name: "description", widget: "markdown"}
    - name: "blogs"
      label: "blogs"
      file: "app/content/blogs.md"
      fields:
        - name: "blog"
          label: "blog"
          widget: "list"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Date", name: "date", widget: "datetime" }
            - { label: "Content", name: "content", widget: "markdown" }
            - label: "Image"
              name: "image" 
              widget: "list"
              fields:
                - {label: "Image", name: "image", widget: "image"}
  - name: "dashboard"
    label: "Dashboard"
    files:
    - label: "Features"
      name: "features"
      file: "app/content/dashboard/dashboardFeatures.md"
      fields:
      - label: "Feature"
        name: "DashboardFeature"
        widget: "list"
        fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Icon", name: "icon", widget: "image" }
    - label: "Section1"
      name: "section1"
      file: "app/content/dashboard/section1.md"
      fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "content", widget: "string"}
      - label: "Images"
        name: "images"
        widget: "list"
        min: 1
        max: 1
        fields:
        - {label: "image", name: "image", widget: "image"}
    - label: "Section3"
      name: "section3"
      file: "app/content/dashboard/section3.md"
      fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
    - label: "Section4"
      name: "section4"
      file: "app/content/dashboard/section4.md"
      fields:
      - label: "Section"
        name: "section"
        widget: "list"
        min: 1
        max: 2
        fields:
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Content", name: "content", widget: "markdown"}
        - {label: "Link", name: "link", widget: "string"}
        - {label: "Link Text", name: "linkText", widget: "string"}
  - name: 'demoForm'
    label: 'Demo Form'
    files:
    - label: "Form"
      name: "form"
      file: 'app/content/forms/demoForm.md'
      fields:
      - label: 'Form Title'
        name: 'title'
        widget: 'string'        
      - label: 'Form Content'
        name: 'content'
        widget: 'markdown'
      - label: 'Form Fields (min = 1)'
        name: 'fields'
        widget: 'list'
        fields:
        - label: "Row Name"
          name: "row_name"
          widget: "string"
        - label: 'Row'
          name: 'row'
          widget: 'list'
          min: 1
          max: 2
          fields:
          - label: 'Field Name'
            name: 'name'
            widget: 'string'
          - label: 'Field Label'
            name: 'label'
            widget: 'string'
          - label: 'Field Type'
            name: 'type'
            widget: 'select'
            options:
            - 'text'
            - 'email'
            - 'number'
            - 'password'
            - 'url'
            - 'tel'
            - 'color'
            - 'date'
            - 'time'
            - 'datetime-local'
            - 'month'
            - 'week'
            - 'textarea'
            - 'file'
            - 'dropdown'
          - name: 'dropdown_values'
            label: 'Dropdown Values'
            widget: 'list'
            required: false
            fields:
            - { label: 'Value', name: 'value', widget: 'string' }
            - { label: 'Label', name: 'label', widget: 'string' }
      - name: "privacy"
        label: "Privacy Policy URL"
        widget: "string"
        required: false
  - name: "homepageSections"
    label: "Homepage Sections"
    files:
      - label: "Homepage Sections"
        name: "homepageSections"
        file: "content/dashboard/homepageSections.md"
        fields:
          - label: "Sections"
            name: "sections"
            widget: "list"
            types:
              - label: "Hero Section"
                name: "hero"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "hero" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Content", name: "content", widget: "string" }
                  - label: "Images"
                    name: "images"
                    widget: "list"
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
              - label: "Features Section"
                name: "features"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "features" }
                  - { label: "Title", name: "title", widget: "string" }
                  - label: "Features"
                    name: "features"
                    widget: "list"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Icon", name: "icon", widget: "image" }
              - label: "Image With Text Section"
                name: "imageWithText"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "imageWithText" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Content", name: "content", widget: "markdown" }
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Button Text", name: "buttonText", widget: "string", required: false }
                  - { label: "Button Link", name: "buttonLink", widget: "string", required: false }
              - label: "Promo Section"
                name: "promo"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "promo" }
                  - label: "Promos"
                    name: "promos"
                    widget: "list"
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Content", name: "content", widget: "markdown" }
                      - { label: "Link", name: "link", widget: "string" }
                      - { label: "Link Text", name: "linkText", widget: "string" }
